In [4]:
from sklearn.datasets import load_iris
iris_data= load_iris()
print('Keys of iris_dataset: \n{}'.format(iris_data.keys()))

Keys of iris_dataset: 
dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [5]:
print(iris_data['DESCR'][:193]+ '\n...')

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive 
...


In [6]:
print('Target names: {}'.format(iris_data['target_names']))

Target names: ['setosa' 'versicolor' 'virginica']


In [7]:
print('Feature names: \n{}'.format(iris_data['feature_names']))

Feature names: 
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [8]:
print('Type of data: {}'.format(type(iris_data['data'])))

Type of data: <class 'numpy.ndarray'>


In [9]:
print('Shape of data: {}'.format(iris_data['data'].shape))

Shape of data: (150, 4)


In [11]:
print('First five columns of data: \n{}'.format(iris_data['data'][:5]))

First five columns of data: 
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [12]:
print('Type of target: {}'.format(type(iris_data['target'])))

Type of target: <class 'numpy.ndarray'>


In [13]:
print('Shape of target: {}'.format(iris_data['target'].shape))

Shape of target: (150,)


In [14]:
print('Target: {}'.format(iris_data['target']))

Target: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [15]:
print('The meaning of the numbers: {}'.format(iris_data['target_names']))

The meaning of the numbers: ['setosa' 'versicolor' 'virginica']


In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris_data['data'], iris_data['target'], random_state=0)

In [18]:
print('X_train shape: {}'.format(X_train.shape))
print('y_train shape: {}'.format(y_train.shape))

X_train shape: (112, 4)
y_train shape: (112,)
